export default function DisclaimerPage() {
  return (
    <div className="container mx-auto px-4 py-16 max-w-4xl">
      <div className="space-y-8">
        <div className="text-center space-y-4">
          <h1 className="text-4xl font-bold text-gray-900 dark:text-white">
            Disclaimer
          </h1>
          <p className="text-xl text-gray-600 dark:text-gray-400">
            Important information about using XFoli AI
          </p>
        </div>

        <div className="bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg p-6">
          <div className="flex items-start space-x-3">
            <div className="flex-shrink-0">
              <svg className="w-6 h-6 text-yellow-600 dark:text-yellow-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L4.082 16.5c-.77.833.192 2.5 1.732 2.5z" />
              </svg>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-yellow-800 dark:text-yellow-200 mb-2">
                Important Notice
              </h3>
              <p className="text-yellow-700 dark:text-yellow-300">
                XFoli AI is provided for informational and educational purposes only. This application is not intended to provide financial, investment, or trading advice.
              </p>
            </div>
          </div>
        </div>

        <div className="space-y-6">
          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">
              Not Financial Advice
            </h2>
            <div className="prose prose-gray dark:prose-invert max-w-none">
              <p>
                The information, analysis, and AI-generated content provided by XFoli AI do not constitute financial, investment, legal, tax, or trading advice. We are not licensed financial advisors, and nothing on this platform should be interpreted as personalized investment recommendations.
              </p>
              <p>
                All investment decisions should be made based on your own research, risk tolerance, and financial situation. You should consult with qualified financial professionals before making any investment decisions.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">
              Data Accuracy and Limitations
            </h2>
            <div className="prose prose-gray dark:prose-invert max-w-none">
              <p>
                <strong>Market Data:</strong> Stock prices, financial data, and market information are sourced from third-party providers and may be delayed, inaccurate, or incomplete. We do not guarantee the accuracy, completeness, or timeliness of any market data.
              </p>
              <p>
                <strong>AI Analysis:</strong> Our AI-powered analysis is generated by machine learning models that may produce inaccurate, incomplete, or misleading information. AI models can &ldquo;hallucinate&rdquo; or misinterpret data, leading to incorrect conclusions.
              </p>
              <p>
                <strong>Real-time Data:</strong> Data provided may not be real-time and could have significant delays. Do not rely on this data for time-sensitive trading decisions.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">
              Investment Risks
            </h2>
            <div className="prose prose-gray dark:prose-invert max-w-none">
              <p>
                All investments carry risk, including the potential loss of principal. Past performance does not guarantee future results. Stock prices can fluctuate significantly and you may lose money.
              </p>
              <p>
                Key risks include but are not limited to:
              </p>
              <ul>
                <li>Market volatility and price fluctuations</li>
                <li>Company-specific risks and business failures</li>
                <li>Economic and political factors</li>
                <li>Liquidity risks</li>
                <li>Currency and inflation risks</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">
              User Responsibility
            </h2>
            <div className="prose prose-gray dark:prose-invert max-w-none">
              <p>
                By using XFoli AI, you acknowledge and agree that:
              </p>
              <ul>
                <li>You are solely responsible for all investment decisions and their consequences</li>
                <li>You will conduct your own research and due diligence</li>
                <li>You understand the risks involved in investing</li>
                <li>You will not hold XFoli AI liable for any financial losses</li>
                <li>You will verify all information independently before making decisions</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">
              Limitation of Liability
            </h2>
            <div className="prose prose-gray dark:prose-invert max-w-none">
              <p>
                To the fullest extent permitted by law, XFoli AI and its creators disclaim all warranties and shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from the use of this application, including but not limited to financial losses, missed opportunities, or data inaccuracies.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">
              Educational Purpose
            </h2>
            <div className="prose prose-gray dark:prose-invert max-w-none">
              <p>
                XFoli AI is designed as an educational tool to help users learn about portfolio tracking and financial analysis. It should be used for educational and informational purposes only, not as a primary source for investment decisions.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">
              Updates to This Disclaimer
            </h2>
            <div className="prose prose-gray dark:prose-invert max-w-none">
              <p>
                This disclaimer may be updated from time to time. Continued use of XFoli AI constitutes acceptance of any changes to this disclaimer.
              </p>
            </div>
          </section>
        </div>

        <div className="border-t border-gray-200 dark:border-gray-800 pt-8">
          <p className="text-sm text-gray-500 dark:text-gray-400 text-center">
            Last updated: {new Date().toLocaleDateString()}
          </p>
        </div>
      </div>
    </div>
  )
} 